---
  url: "http://testfire.net/bank/login.aspx"
  form: 
    id: "login"
    fields: 
      passw: "Demo1234"
      uid: "jsmith"
  options: 
    check_url: true
    check_pattern: "/Sign Off|MY ACCOUNT/"
